name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest
    env: 
     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright (${{ matrix.browser }})
        run: npx playwright test --project=${{ matrix.browser }}
      - name: Upload HTML report (${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.browser }}
          path: playwright-report/
          retention-days: 30
      - name: Notify Slack (${{ matrix.browser }})
        if: always()
        uses: act10ns/slack@v2
        with:
          channel: '#cicd-playwright'
          status: ${{ job.status }}
          message: |
            ${{ job.status == 'success' && '✅' || job.status == 'failure' && '❌' || '🚫' }}
            Playwright (${{ matrix.browser }}) finished with *${{ job.status }}*
            Repo: <https://github.com/${{ github.repository }}|${{ github.repository }}>
            Branch: <https://github.com/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>
            Commit: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha::7 }}>
            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Open run> •
            <https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts|Download report>

